{
 "title": "Kubernetes Kafka resource metrics",
 "description": "Monitors Kafka metrics from Prometheus. Shows active controllers, partitions, ISR shrink rate, purgatory size etc. Uses JMX exporter.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_pod_name",
    "label": "Kafka Broker",
    "query": "label_values(kafka_server_kafkaserver_brokerstate{}, kubernetes_pod_name)"
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": "label_values(kafka_log_logstartoffset{}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "ISR shrink rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrshrinks_total{kubernetes_pod_name=\"$kubernetes_pod_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "ISR expansion rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrexpands_total{kubernetes_pod_name=\"$kubernetes_pod_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Delayed Fetch operation purgatory size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{kubernetes_pod_name=\"$kubernetes_pod_name\"}"
    }
   ]
  },
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{kubernetes_pod_name=\"$kubernetes_pod_name\"}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{kubernetes_pod_name=\"$kubernetes_pod_name\", topic=~\"$topic$\"})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{kubernetes_pod_name=\"$kubernetes_pod_name\"}"
    }
   ]
  },
  { "title": "Topic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$topic Bytes In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{kubernetes_pod_name=\"$kubernetes_pod_name\",topic=~\"$topic$\"})"
    }
   ]
  },
  {
   "title": "$topic Bytes out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{kubernetes_pod_name=\"$kubernetes_pod_name\", topic=~\"$topic\"})"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Unclean leader election per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kafka_controller_controllerstats_uncleanleaderelectionspersec{kubernetes_pod_name=\"$kubernetes_pod_name\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Fetch requests in Purgatory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_fetch{kubernetes_pod_name=\"$kubernetes_pod_name\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Consumer requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Local request consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems_request_fetchconsumer_count{kubernetes_pod_name=\"$kubernetes_pod_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Remote request consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems_request_fetchconsumer_count{kubernetes_pod_name=\"$kubernetes_pod_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request queue consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems_request_fetchconsumer_count{kubernetes_pod_name=\"$kubernetes_pod_name\"}[1m]))"
    }
   ]
  }
 ]
}