apiVersion: banzaicloud.banzaicloud.io/v1alpha1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app: "{{ template "kafka-spotguide.fullname" . }}"
    chart: "{{ include "kafka-spotguide.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: kafka
spec:
  zkAddresses:
    - "{{.Values.zk.url}}"
  brokerConfigs:
  {{$brokerIds := repeat (int .Values.brokers.replicas) "_" | split "_"}}
  {{range $i,$v := $brokerIds}}
    - image: "{{$.Values.image.repository}}:{{$.Values.image.tag}}"
      id: {{trimPrefix "_" $i}}
      config: |
        {{- $.Values.brokers.config | nindent 8}}
      storageConfigs:
        - mountPath: "/kafka-logs"
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "{{$.Values.brokers.disk.size}}"
  {{- end}}
  listenersConfig:
{{- if or (eq (.Values.brokers.ssl.mechanism) "External") (eq (.Values.brokers.ssl.mechanism) "Internal/External") }}
    externalListeners:
      - type: "ssl"
        name: "external"
        externalStartingPort: 19090
        containerPort: 9094
{{- else }}
    externalListeners:
      - type: "plaintext"
        name: "external"
        externalStartingPort: 19090
        containerPort: 9094
{{- end}}
{{- if or (eq (.Values.brokers.ssl.mechanism) "Internal") (eq (.Values.brokers.ssl.mechanism) "Internal/External") }}
    internalListeners:
      - type: "ssl"
        name: "ssl"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
{{- else }}
    internalListeners:
      - type: "plaintext"
        name: "plaintext"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
{{- end }}
{{- if or (eq (.Values.brokers.ssl.mechanism) "External") (eq (.Values.brokers.ssl.mechanism) "Internal/External") (eq (.Values.brokers.ssl.mechanism) "Internal")}}
    sslSecrets:
      tlsSecretName: "{{.Values.brokers.ssl.secretName}}"
      jksPasswordName: "{{.Values.brokers.ssl.jksSecretName}}"
{{- end }}
  serviceAccount: ""